Add maxResults limit option
apify-projects/store-expedia-hotels-com pull request #2
Opened 2024-03-17 09:30 UTC by HamzaAlwan

2024-03-17 09:34 UTC, Fayj3 commented
We will push this on April 1st in order to avoid breaking any current stuff 
Thank you for the work @HamzaAlwan

2024-03-18 16:29 UTC, mvolfik requested changes
Perhaps I'm missing something, but why are we adding the global maxResults into the input? PPR actors have the "system" maximum paid results setting, and we need to honor that, and then this input fields would just duplicate the same functionality

![image](https://github.com/apify-projects/store-expedia-hotels-com/assets/31281386/8c853120-49a7-4f62-b2c0-d7178e15d13f)

2024-03-18 20:51 UTC, HamzaAlwan commented
> Perhaps I'm missing something, but why are we adding the global maxResults into the input? PPR actors have the "system" maximum paid results setting, and we need to honor that, and then this input fields would just duplicate the same functionality

Thanks, I totally forgot about that, updated the code

2024-04-08 10:06 UTC, mvolfik reviewed
@HamzaAlwan I can do the changes and merge this, I'd just love if you could answer the Qs, because maybe I've been doing this all wrong for all the Actors where I did this. Maybe I'll run some experiments how this behaves in the afternoon

also sorry I didn't get around to do this earlier

2024-04-08 10:06 UTC, mvolfik commented on src/utils.ts
> +    await crawler.autoscaledPool?.abort();
There is `.teardown()` directly on crawler, which aborts the autoscaledPool, and also cleans up other resources. I guess that would be preferred?

Also, did you experience somewhere that the 5s sleep is really necessary? This is honest question - I always thought that crawler stop gives the already-running requests time to finish, but it's just an assumption, I'm not at all sure

2024-04-08 10:06 UTC, mvolfik commented on src/handler.ts
> +            scrapeSettings.totalPushedResults += reviews.length;
shouldn't this update be before the if(), so that we abort if the reviews from this request caused us to reach the limit?

2024-04-08 10:06 UTC, mvolfik commented on src/main.ts
> +    }],
I hope that this shouldn't be necessary, when we teardown the crawler

or is our SDK really _that_ unhelpful?

2024-04-08 15:46 UTC, mvolfik commented on src/main.ts
> +    }],
confirmed with `console.log`s: after `crawler.teardown()`, no requests enter the prenavigation hook

2024-04-08 16:21 UTC, mvolfik commented on src/utils.ts
> +    await crawler.autoscaledPool?.abort();
hm, so the cleanest way to let everything finish correctly would be this:

```js
async function stop(crawler) {
  await crawler.autoscaledPool.pause();
  await crawler.teardown();
}

// from request handler:

// eslint-disable-next-line @typescript-eslint/no-floating-promises
stop(crawler); 
```

`.pause()` waits for all pending requests to finish, without starting any new ones. However, that would never resolve inside the request handler - so we need to start the `stop()` in background, with a floating promise.

However, I think it is justifiable to ignore requests that don't finish cleanly in this type of public Actors - we are just scraping data, and as soon as we scraped enough data, we can just exit as quickly as possible. So IMO it is really best to call `crawler.teardown()`, as long as it's called **after** the `await pushData()` in the request that triggered the limit. Then you don't need to write any code to empty the request queue or sleep to ensure that data is persisted.

Sorry for such a monologue, I'd love to get a sanity check from you. Then I'll push my refactor of this. Thanks for your help with this, though!

2024-04-15 12:19 UTC, merged